[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

# Ensure all dependencies are installed
[context.production]
  command = "npm ci && npm run build"

[context.deploy-preview]
  command = "npm ci && npm run build"

[context.branch-deploy]
  command = "npm ci && npm run build"